"""Order

Revision ID: 257bcf7a6a4a
Revises: e64c8525d9cd
Create Date: 2023-07-02 00:02:24.213921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257bcf7a6a4a'
down_revision = 'e64c8525d9cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
