"""add text to order

Revision ID: 3dacca1c88a9
Revises: cad0f079181c
Create Date: 2023-07-01 23:45:19.703563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dacca1c88a9'
down_revision = 'cad0f079181c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'text')
    # ### end Alembic commands ###
