"""Initial commit

Revision ID: 706c260e94a5
Revises: 8d2787d5a106
Create Date: 2023-06-29 16:42:27.083913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706c260e94a5'
down_revision = '8d2787d5a106'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_registered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_registered')
    # ### end Alembic commands ###
