"""Order

Revision ID: cad0f079181c
Revises: 706c260e94a5
Create Date: 2023-07-01 22:15:23.205820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad0f079181c'
down_revision = '706c260e94a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('type', sa.String(), nullable=True))
    op.add_column('order', sa.Column('user', sa.String(), nullable=True))
    op.create_foreign_key(None, 'order', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'user')
    op.drop_column('order', 'type')
    # ### end Alembic commands ###
