"""Order ID to Int

Revision ID: e64c8525d9cd
Revises: 3dacca1c88a9
Create Date: 2023-07-01 23:50:13.481260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64c8525d9cd'
down_revision = '3dacca1c88a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
